apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example
resources:
  - example-server.yaml
  - example-server-mounted.yaml
patches:
  - path: patches/patch-configmap.yaml
    target:
      kind: ConfigMap
      name: example-server-config
  - path: patches/patch-mounted-configmap.yaml
    target:
      kind: ConfigMap
      name: example-server-mounted-config